### PR TITLE
New space station model, doors and shoot changed from mouse to magnetic ...

### PR DESCRIPTION
**Pull request by calthomson**
...trigger

### CODE REVIEW

**Comment by JimFung** [comment]
I thought the new model would be one piece. I can still select individual floor panels.

**Comment by calthomson** [comment]
There are individual pieces parented (childed?) to the overall model, this is to be expected I think. It's how we'll animate things like the doors that open in the middle.

**Comment by JimFung** [comment]
Okay. looks good then

**Comment by JimFung** [comment]
can this branch be deleted?

**Comment by calthomson** [comment]
Done

**Pull request closed without merging**
